'use client'

import './globals.css'
import { Montserrat } from 'next/font/google'
import NavBar from '../components/NavBar'
import Script from 'next/script'
import Head from 'next/head'



const montserrat = Montserrat({ 
  subsets: ['latin'],
  variable: "--font-mont "
 })

export const metadata = {
  title: 'Personal Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    </Head>
      <body className={`${montserrat.className} bg-light dark:bg-dark w-full flex flex-col min-h-screen`}>
        <NavBar />
        <div className='xl:p-24 lg:p-16 mb:p-12 sm:p-8 flex-grow'>
          {children}
        </div>
          
      </body>
    </html>
  )
}
